### ISSUE TITLE
object contains unparsed element in datadog_service_level_objective resource

### ISSUE THREAD

**Issue by lfgarciaBC** [DataDog/terraform-provider-datadog#2378] opened 2024-04-22 22:14 UTC
### Datadog Terraform Provider Version

v3.38.0

### Terraform Version

v1.7.5

### What resources or data sources are affected?

- datadog_service_level_objective

### Terraform Configuration Files

```hcl
resource "datadog_service_level_objective" "slo_test" {
  name = "SLO test"
  type = "metric"
  query {
    numerator   = "sum:aws.applicationelb.request_count{*} by {app}.as_count() - sum:aws.applicationelb.httpcode_elb_5xx{*} by {app}.as_count()"
    denominator = "sum:aws.applicationelb.request_count{*} by {app}.as_count()"
  }

  thresholds {
    timeframe = "7d"
    target    = 99.95
    warning   = 99.96
  }
}
```

### Relevant debug or panic output

```
╷
│ Error: object contains unparsed element: map[count:map[good_events_query:map[formulas:[map[formula:(query1 - query2)]] queries:[map[data_source:metrics name:query1 query:sum:aws.applicationelb.request_count{*}by{app}.as_count()] map[data_source:metrics name:query2 query:sum:aws.applicationelb.httpcode_elb_5xx{*}by{app}.as_count()]]] total_events_query:map[formulas:[map[formula:query1]] queries:[map[data_source:metrics name:query1 query:sum:aws.applicationelb.request_count{*}by{app}.as_count()]]]]]
│ 
│   with module.dashboards.module.reliability-api.datadog_service_level_objective.slo_test,
│   on dashboards/reliability-api/main.tf line 174, in resource "datadog_service_level_objective" "slo_test":
│  174: resource "datadog_service_level_objective" "slo_test" {
│ 
```

### Expected Behavior

plan and apply succeeds without error

### Actual Behavior

`terraform apply` throws an error even when the resource was created successfully 
![image](https://github.com/DataDog/terraform-provider-datadog/assets/59662276/f8d55ada-f330-4c45-a676-7dc352d934fc)

### Steps to Reproduce

1. `terrafrom plan` creates the plan successfully
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.dashboards.module.reliability-api.datadog_service_level_objective.slo_test will be created
  + resource "datadog_service_level_objective" "slo_test" {
      + id                = (known after apply)
      + name              = "SLO test"
      + target_threshold  = (known after apply)
      + timeframe         = (known after apply)
      + type              = "metric"
      + warning_threshold = (known after apply)

      + query {
          + denominator = "sum:aws.applicationelb.request_count{*} by {app}.as_count()"
          + numerator   = "sum:aws.applicationelb.request_count{*} by {app}.as_count() - sum:aws.applicationelb.httpcode_elb_5xx{*} by {app}.as_count()"
        }

      + thresholds {
          + target          = 99.95
          + target_display  = (known after apply)
          + timeframe       = "7d"
          + warning         = 99.96
          + warning_display = (known after apply)
        }
    }
```
2. `terraform apply` throws the error

I started getting this error since this week, before that `terraform apply` was completed successfully

**Comment by therve** [comment] 2024-04-23 06:14
Duplicate of #2377

**Closed by therve** 2024-04-23 06:14 UTC
Labels: bug
