### ISSUE TITLE
Terraform is not able to find the desired provider for datadog. Could not retrieve the list of available versions for provider hashicorp/datadog: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/datadog

### ISSUE THREAD

**Issue by surajtikoo** [DataDog/terraform-provider-datadog#1405] opened 2022-04-05 10:10 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see https://www.terraform.io/community.html.

### Affected Resource(s)

Please list the resources as a list, for example:
-   datadog_synthetics_test

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "datadog_synthetics_test" "test_api" {
  type    = "api"
  subtype = "http"
  request_definition {
    method = "GET"
    url    = "https://www.example.org"
  }
  request_headers = {
    Content-Type   = "application/json"
    Authentication = "Token: 1234566789"
  }
  assertion {
    type     = "statusCode"
    operator = "is"
    target   = "200"
  }
  locations = ["aws:eu-central-1"]
  options_list {
    tick_every = 900

    retry {
      count    = 2
      interval = 300
    }

    monitor_options {
      renotify_interval = 100
    }
  }
  name    = "An API test on example.org"
  message = "Notify @pagerduty"
  tags    = ["foo:bar", "foo", "env:test"]

  status = "live"
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

What should have happened?

### Actual Behavior

What actually happened?

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform init`

**Comment by therve** [comment] 2022-04-05 11:55
Hi,

Can you share the provider instantiation? Thanks.

**Comment by surajtikoo** [comment] 2022-04-05 12:16
@therve  below is the provider and version i am using
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
      version = "3.10.0"
    }
  }

**Comment by therve** [comment] 2022-04-05 13:05
Sorry I cant' reproduce. Can you try upgrading your Terraform CLI? 0.14.0 is pretty old.

**Comment by therve** [comment] 2022-04-05 13:37
Is it a fresh workspace, or did you use an older terraform version before? What does `terraform init` tells you?

**Comment by surajtikoo** [comment] 2022-04-05 13:58
Yes, it is a fresh workspace. Below is the error for reference.


Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/datadog: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/datadog
│
│ Did you intend to use datadog/datadog? If so, you must specify that source address in each module which requires that provider. To see which modules are currently
│ depending on hashicorp/datadog, run the following command:
│     terraform providers
╵

**Comment by therve** [comment] 2022-04-05 14:01
Are you sure you don't have another `terraform` block configuration in your workspace? Or maybe a global .terraformrc configuration file?

**Comment by mujina** [comment] 2022-04-13 17:01
Seeing the same issue
Terraform v1.1.5
on windows_amd64

$ terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding datadog/datadog versions matching "3.10.0"...
- Finding latest version of hashicorp/datadog...
- Installing datadog/datadog v3.10.0...
- Installed datadog/datadog v3.10.0 (signed by a HashiCorp partner, key ID FB70BE941301C3EA)

Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/datadog: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/datadog
│
│ Did you intend to use datadog/datadog? If so, you must specify that source address in each module which requires that provider. To see which modules are currently depending on hashicorp/datadog, run the following command:
│     terraform providers



```
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
      version = "3.10.0"
    }
  }
}

provider "datadog" {
  api_url = "https://api.datadoghq.eu/"
}
```

**Comment by therve** [comment] 2022-04-13 17:03
It's a configuration problem, generally it happens when you have several modules.

**Comment by mujina** [comment] 2022-04-14 07:46
New repo for me, all I have is the one module, just referencing a local source for now. Any workaround do you know?

```
module "datadog_metric_monitor" {
  source = "../aws-module-datadog/metric-monitor"
  ....
```

**Comment by therve** [comment] 2022-04-14 07:48
The provider needs to be defined inside your local source.

**Comment by thomasbell1985** [comment] 2022-04-15 00:17
I have this same problem with the datadog provider. My provider setup looks like the following:

```sh
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.27"
    }
    datadog = {
      source  = "terraform-provider-datadog/datadog"
      version = "3.10.0"
    }
  }
  required_version = ">= 1.1.7"
  backend "s3" {}
}
```

**Comment by therve** [comment] 2022-04-15 07:55
> ```shell
>       source  = "terraform-provider-datadog/datadog"
> ```

This needs to be `datadog/datadog`.

**Comment by mujina** [comment] 2022-04-19 08:41
For me the problem still exists if I try and use the datadog_monitor resource in a module, however if use the resource directly it's not a problem. Do we know if there's a workaround for this situation?

**Comment by robmosca-travelperk** [comment] 2022-04-27 12:48
Also having the same problem with this config:
```
datadog = {
      source  = "DataDog/datadog"
      version = "= 3.11.0"
    }
```

**Comment by uro** [comment] 2022-05-07 20:59
For me, the solution was simple but not obvious. 

At first, the initialisation fails, but it's a physical configuration problem in your terraform code. 
In my case, commenting out the whole datadog module section and defining an empty one confirmed it's an issue with the code itself. 

What I did wrong: I loaded the datadog resources inside my "local datadog" module. Then used this local module within the project. I forgot to add the "terraform provider" section inside the local module. I did it just on the project root directory. 

Adding the provider section to my module sorted out the issue.

**Comment by PeterDMTFX** [comment] 2022-05-31 11:48
I also have this problem.  Had datadog provider specified in the root module:
`terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
    }
    aws = {
      source = "hashicorp/aws"
    }
  }
}`
Was working ok, then decided to split some of the datadog resources out into a module at which point tf init through out the above error.  I worked around this by declaring the provider in the child module.  According to the documentation the declaration in the  root module should be inherited implicitly by the child.  https://www.terraform.io/language/modules/develop/providers  I'm not sure why it's necessary to declare it again.

**Comment by alexpyoung** [comment] 2022-06-08 15:31
I am only using Datadog resources in a child module, and only declaring the provider in the child module worked
```
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
    }
  }
}
```

**Comment by waneal** [comment] 2022-06-21 08:57
I also faced this problem.  My configuration file is below.

```terraform
terraform {
  required_version = "~> 1.1.7"

  backend "s3" {
    bucket = "YOUR_BUCKET"
    key    = "YOUR_TFSTATE"
    region = "ap-northeast-1"
  }

  required_providers {
    datadog = {
      source  = "DataDog/datadog"
      version = "3.12.0"
    }
  }
}

provider "aws" {
  region = "ap-northeast-1"
}

provider "datadog" {
  alias = "main"
  api_key = var.datadog_api_key
  app_key = var.datadog_app_key
}

module "main" {
  source                = "../../module"
}

```

In this case, I understood that I have to define `required_providers` in local module as @therve mentioned [it](https://github.com/DataDog/terraform-provider-datadog/issues/1405#issuecomment-1098810079), and I found the related [issue](https://github.com/DataDog/terraform-provider-datadog/issues/791#issuecomment-754873306).

**Comment by jtreguboff** [comment] 2022-08-23 19:43
The issue surrounding this seems to be a problem with the specific location that's being called in TF:

```
│ Could not retrieve the list of available versions for provider hashicorp/datadog: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/datadog
│
│ Did you intend to use datadog/datadog? If so, you must specify that source address in each module which requires that provider. To see which modules are currently
│ depending on hashicorp/datadog, run the following command:
│ terraform providers
```
This location:
`registry.terraform.io/hashicorp/datadog`

should be the following from what I understand:
`https://registry.terraform.io/providers/DataDog/datadog`

but it seems that adding the provider to the root module and not the child module causes this. What's frustrating is that terraform will error out if I remove my DD module and causes issues. Not sure if this is something terraform needs to address on their end or if datadog can fix this issue.

**Comment by hjkatz** [comment] 2022-09-26 19:51
I just went through this annoying quirk with the interaction between `terraform` and `terragrunt` for the `required_providers` block specifically in the `terraform {}` block.

Here's what I came up with:

In the root, I have terragrunt generate a `required_providers_override.tf` file with the following content:

```
    terraform {    
      required_providers {    
        datadog = {    
          source  = "DataDog/datadog"    
        }    
      }    
    }
```

Note: The name of this file is _important_. Files named `*_override.tf` are processed and merged _last_ when `terraform` is invoked.
See:
* https://www.terraform.io/language/files/override
* https://stackoverflow.com/questions/66770564/using-terragrunt-generate-provider-block-causes-conflicts-with-require-providers

Then, in each module I have a `terraform.tf` file written that _also_ declares a `required_providers.tf` block:

```
terraform {    
  required_providers {    
    datadog = {    
      source = "DataDog/datadog"    
    }    
  }
}
```

Here's the final directory structure:

```
$ tree
./
├── global/
│   └── logs/
│       └── indexes/
│           └── terragrunt.hcl
├── modules/
│   ├── logs_index/
│   │   ├── main.tf
│   │   ├── output.tf
│   │   ├── terraform.tf
│       └── vars.tf
└── terragrunt.hcl
```

What this looks like to terraform:

```
$ tree

.terragrunt-cache/
└── pvN4MZH0iKL7jeedjcEmma-ZWZg/
    └── VgLK7GJVCSJlfH7SIMYw93xZvNo/
        ├── logs_index/
        │   ├── main.tf
        │   ├── output.tf
        │   ├── terraform.tf
        │   └── vars.tf
        └── logs_indexes_config/
            ├── main.tf
            ├── terraform.tf
            ├── terragrunt.hcl
            ├── terragrunt_providers.tf
            ├── terragrunt_required_providers_override.tf  # <-- This overrides the required_providers {} block in `terraform.tf`
            ├── terragrunt_state.tf
            └── vars.tf
```

Now both `terraform` and `terragrunt` are happy.

Terraform can see in each module a `terraform.tf` with contents `terraform { required_providers { ... } }` where the `DataDog/datadog` provider path is properly written.
Terragrunt is happy because it generates the `terragrunt_required_providers_override.tf` file which is used (and processed/merged _last_) when `terragrunt plan` and other commands are invoked.

I seriously hope this helps someone else.

**Comment by Marwen94** [comment] 2022-10-11 10:48
Same issue encountered in our project : 

Terraform version : `Terraform v1.3.2
on darwin_amd64
`

Config block : 

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.26.0"
    }
    datadog = {
      source = "datadog/datadog"
    }
  }

  backend "s3" {
    bucket         = "xxxxx"
    key            = "xxxxx"
    dynamodb_table = "xxxxx"
    region         = "xxxxx"
  }
  required_version = ">= 1.0"
}

```


Although Terraform finds the provider  : 


```
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/aws versions matching "~> 4.26.0"...
- Finding datadog/datadog versions matching "2.18.1"...
- Finding latest version of hashicorp/datadog...
- Installing datadog/datadog v2.18.1...
- Installed datadog/datadog v2.18.1 (signed by a HashiCorp partner, key ID FB70XXXXXXX)
- Installing hashicorp/aws v4.26.0...
- Installed hashicorp/aws v4.26.0 (signed by HashiCorp)
```

It still raises this error : 

```
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/datadog: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/datadog
│ 
│ Did you intend to use datadog/datadog? If so, you must specify that source address in each module which requires that provider. To see which modules are currently
│ depending on hashicorp/datadog, run the following command:
│     terraform providers
```

**Comment by imgeraldalinio** [comment] 2022-10-26 14:56
Hello, the same issue here encountered from our project

`╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider
│ hashicorp/datadog: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/datadog
│ 
│ Did you intend to use datadog/datadog? If so, you must specify that source
│ address in each module which requires that provider. To see which modules
│ are currently depending on hashicorp/datadog, run the following command:
│     terraform providers
╵`

My provider configuration:
`terraform {
   required_version = ">= 1.1.5, < 1.3.0" 

      required_providers {
         datadog = {
            source  = "DataDog/datadog"
            version = ">= 2.10, < 4"
         }
         
         # https://registry.terraform.io/providers/hashicorp/aws/3.74.2
         aws = {
         source = "hashicorp/aws"
         version = ">= 3.74.2, < 4.0" 
         }
     }
  }
`

`provider "datadog" {
  api_key = var.dd_api_key
  app_key = var.dd_app_key
}`

**Comment by imgeraldalinio** [comment] 2022-10-26 19:44
Yeah, I'm using a module and I followed this example https://github.com/scribd/terraform-aws-datadog/blob/master/examples/full_integration/main.tf

But still getting the same error
![image](https://user-images.githubusercontent.com/38755420/198121634-3f1b7a3a-3af0-4a0e-95fb-cca8b4603381.png)

**Comment by imgeraldalinio** [comment] 2022-10-26 19:57
I solved the error after removing one of my script containing [Datadog AWS Integration](https://github.com/scribd/terraform-aws-datadog/blob/master/main.tf) outside the module. That's so weird, but I like to include my Datadog AWS Integration script inside the module.

**Comment by therve** [comment] 2022-10-27 08:08
You need to have the required_providers section in the module itself, not just outside of it.

**Comment by therve** [comment] 2023-04-05 11:58
Closing this one. As mentioned, the `required_providers` needs to be present everywhere the provider is used, even in dependent modules.

**Closed by therve** 2023-04-05 11:58 UTC
