### ISSUE TITLE
Browser synthetic test creation fails with `'bucketKey' is a required property`

### ISSUE THREAD

**Issue by gabrielhof** [DataDog/terraform-provider-datadog#933] opened 2021-02-17 19:22 UTC
Hi there,

I'm trying to create a basic browser synthetic test, but I'm facing the following error:

```
Step 0 has invalid params: 'bucketKey' is a required property
```

### Terraform Version

```
➜ terraform -v
Terraform v0.14.6
+ provider registry.terraform.io/datadog/datadog v2.21.0
```

### Affected Resource(s)

- datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "basic_browser_test" {
  type = "browser"
  name = "Basic Browser Test"
  status = "live"

  locations = ["aws:us-east-2"]
  device_ids = ["chrome.laptop_large"]

  options_list {
    tick_every = 3600
  }

  message = <<-EOT
  *Basic Browser Test*

  {{#is_alert}}
  :red-alert: Basic Browser Test is failing.
  {{/is_alert}}

  {{#is_alert_recovery}}
  :green-alert: Basic Browser Test has now recovered.
  {{/is_alert_recovery}}
  EOT

  request_definition {
    method = "GET"
    url = "https://google.com"
  }

  browser_step {
    type = "typeText"
    name = "Input something in the search field"

    params {
      element = jsonencode({
        userLocator = {
          values = [{
            type = "css"
            value = "input[name='q']"
          }]
        }

      })

      value = "Some search"
    }
  }
}

```

### Debug Output

https://gist.github.com/gabrielhof/00b22360384b2bd8344602b926648196

### Panic Output

No panic produced.

### Expected Behavior

The synthetic test should be successfully created with the configured browser step or either the expected value for the `bucketId` property should be present in the documentation.

### Actual Behavior

The synthetic test gets created but without any steps. Also, the created test is not stored inside the terraform state, causing the next executions to duplicate it.

### Steps to Reproduce

1. Created a `main.tf` file with the provided example
2. Execute `terraform apply -auto-approve`

**Comment by gabrielhof** [comment] 2021-02-17 19:25
When trying to specify a random value for the `bucketId` property, I end up getting a different error:
```
Error: error creating synthetics test: 400 Bad Request: {"errors": ["Step 0 has invalid params: Additional properties are not allowed (u'bucketId' was unexpected)"]}
```

It seems this property is both required and not expected to be there (or I'm proving an invalid value for it).

**Comment by faizhasim** [comment] 2021-09-02 06:02
Is there any plan/timeline to resolve this? Let us know if I can help to make PR etc.

**Comment by 1995YogeshSharma** [comment] 2021-09-07 23:14
I also faced same issue. As @faizhasim pointed out the issue is because of multiLocator requirement as "element" (and your solution looks great!)

The easiest way to get around is sadly to just create the test on UI and then use terraformer to import the test as terraform code (and strip it down a bit to remove unnecessary attributes).

Is "multiLocator" a proprietary method used by Datadog to locate element? I couldn't find much information to generate element in the similar format.

**Comment by faizhasim** [comment] 2021-09-07 23:21
Dev in our team also figure out that as long as you pass the multiLocator, even with ab="" (empty string), it would work too. But, not sure whether that's intended by Datadog. 

I think the multiLocator isn't documented and it's part of their custom query/dsl, that get generated when you interact on the UI. There's no way I would use that even if they provide the documentations lol.

**Comment by 1995YogeshSharma** [comment] 2021-10-16 11:21
Hey @huynv9699 ,

Here's the terraformer command to import a synthetic test
`terraformer import datadog --resources=synthetics_test --filter=synthetics_test={{TEST_IDX_IN_URL}} --api-key DD_API_KEY --app-key DD_APP_KEY `

To make it work -
- You install "terraformer" on your system
- Create a synthetic test using datadog UI
- Run the terraformer command mentioned above in a folder, it would create a "generated" folder with terraform code inside it.
- Keep the necessary part from the generated code and add it to your terraform code to create / maintain test using terraform.

**Comment by huynv9699** [comment] 2021-10-17 10:54
@1995YogeshSharma,
the tool is so good, it helped me so much. thanks a lot.

**Comment by dillonbaxendell** [comment] 2022-07-27 14:27
@1995YogeshSharma, thanks for the solution! I'm having troubles using the terraformer command you mentioned above. What is the "TEST_IDX_IN_URL"?

The error I'm getting when I run it is "no such file or directory"

**Comment by 1995YogeshSharma** [comment] 2022-09-18 11:35
Hey @dillonbaxendell , you might have already figured it out.

Just for anyone who stumbles upon this, when you create test using UI, url for the test may look something like https://app.datadoghq.com/synthetics/details/yjs-cv7-jk6, "yjs-cv7-jk6" is TEST_IDX_IN_URL in this case.

> The error I'm getting when I run it is "no such file or directory"
Although, this error should not be related to that

**Comment by skarimo** [comment] 2022-12-29 18:51
Hello all, the mentioned config should now be working with the latest provider version. Going to go ahead and close this issue out but feel free to reapply/re-open if you run into the same issue. Thanks!

**Closed by skarimo** 2022-12-29 18:51 UTC
