### ISSUE TITLE
`ci-pipeline-fingerprints` triggering plan changes in the `datadog_service_definition_yaml` resource

### ISSUE THREAD

**Issue by brettcurtis** [DataDog/terraform-provider-datadog#2117] opened 2023-09-25 14:23 UTC
### Datadog Terraform Provider Version

3.30.0

### Terraform Version

1.5.7

### What resources or data sources are affected?

datadog_service_definition_yaml

### Relevant debug or panic output

Here is the plan output:

```none
Terraform will perform the following actions:

  # datadog_service_definition_yaml.istio["envoy"] will be updated in-place
  ~ resource "datadog_service_definition_yaml" "istio" {
        id                 = "envoy"
      ~ service_definition = <<-EOT
            application: Istio
          - ci-pipeline-fingerprints: []
            contacts:
```

### Expected Behavior

No change

**Comment by nkzou** [comment] 2023-09-25 15:30
Hi, thanks for reporting this. We're aware of the issue and a backend change to fix this is currently being rolled out to prevent the diff. It should resolve within the next day.

**Comment by therve** [comment] 2023-09-28 13:26
Hi, this should be fixed, sorry for the inconvenience.

**Comment by brettcurtis** [comment] 2023-11-08 16:34
I'm now attempting to add these via the 2.2 schema and seeing change on every run:

```hcl
  # datadog_service_definition_yaml.this["istio"] will be updated in-place
  ~ resource "datadog_service_definition_yaml" "this" {
        id                 = "istio"
      ~ service_definition = <<-EOT
            application: Istio
            ci-pipeline-fingerprints:
          +     - g_tXB4tt-IXF
                - 9EGViAQAXz8e
                - DnOOCDnKlu5P
          -     - g_tXB4tt-IXF
   ```

Should I open up another issue for this?

**Comment by nkzou** [comment] 2023-11-10 16:00
we can re-use this issue since its caused by drift of the same field. I was able to reproduce this, will look into a fix.

**Closed** 2023-11-10 21:12 UTC
Labels: bug
