### ISSUE TITLE
object contains unparsed element in datadog_service_level_objective resource

### ISSUE THREAD

**Issue by dgdelahera** [DataDog/terraform-provider-datadog#2377] opened 2024-04-22 09:08 UTC
### Datadog Terraform Provider Version

v3.38.0

### Terraform Version

v1.4.2

### What resources or data sources are affected?

- datadog_service_level_objective

### Terraform Configuration Files

We are using a module to create this resource. However, this error is happening when type is `metric`

```hcl
resource "datadog_service_level_objective" "main" {
  name        = "[${var.account_name}][${local.service}] ${var.name} (${var.environment})"
  type        = var.query != null ? "metric" : "monitor"
  description = "${var.description} (version: ${var.service_version})"

  monitor_ids = var.monitor_ids

  dynamic "query" {
    for_each = var.query == null ? [] : [0]

    content {
      numerator   = lookup(var.query, "numerator", null)
      denominator = lookup(var.query, "denominator", null)
    }
  }

  timeframe         = var.thresholds.0.timeframe
  target_threshold  = var.thresholds.0.target
  warning_threshold = var.thresholds.0.warning

  dynamic "thresholds" {
    for_each = toset(var.thresholds)

    content {
      timeframe = thresholds.value.timeframe
      target    = thresholds.value.target
      warning   = thresholds.value.warning
    }
  }

  tags = local.dd_tags
}
```

### Relevant debug or panic output

```
Error: object contains unparsed element: map[count:map[good_events_query:map[formulas:[map[formula:query1]] queries:[map[data_source:metrics name:query1 query:sum:aws.iot.success{account:<REDACTED>}by{actiontype,rulename}.as_count()]]] total_events_query:map[formulas:[map[formula:(query1 + query2)]] queries:[map[data_source:metrics name:query1 query:sum:aws.iot.success{account:<REDACTED>}by{actiontype,rulename}.as_count()] map[data_source:metrics name:query2 query:sum:aws.iot.failure{account:<REDACTED>}by{actiontype,rulename}.as_count()]]]]]
 
   with module.<REDACTED>[0].datadog_service_level_objective.main,
   on .terraform/modules/<REDACTED>/main.tf line 56, in resource "datadog_service_level_objective" "main":
   56: resource "datadog_service_level_objective" "main" {
 ```

### Expected Behavior

plan/apply succeeds without error

### Actual Behavior

plan/apply terminates with an error.

### Steps to Reproduce

The error started showing up today:

1. Do a terraform plan or terraform apply

**Comment by xebia-progress** [comment] 2024-04-22 09:34
I am facing the same error.

Datadog Terraform Provider Version
v3.38.0

Terraform Version
v1.7.4

```
module.service.datadog_service_level_objective.slo[0]: Creating...

│ Error: object contains unparsed element:
```

I have tried with some of the previous versions of DataDog provider [3.37, 3.36, 3.35] and the same error occurred.
When I browse the /slo page using the DD console, I see that terraform creates a new SLO every time despite the error.

**Comment by HantingZhang2** [comment] 2024-04-22 15:59
This is due to changes on our backend that no longer send out responses that match the expectation of this resource.
SLOs should be able to be created with this resource despite this error. 
We are updating our api libraries and then a fix for terraform resource should follow.

**Comment by xebia-progress** [comment] 2024-04-23 07:15
@HantingZhang2  I imported created SLO to the Terraform state this morning and now it seems to be working fine.

**Comment by nkzou** [comment] 2024-04-23 13:33
Hi all, a fix for this was deployed last evening on the API side - things should be fixed now, with no action needed on the end user side. If you're still having issues, please let us know and we will investigate further. Thanks!

**Comment by charlesverdad** [comment] 2024-04-24 04:24
I am seeing a similar error but for a `datadog_synthetic_test` resource

```
│ Error: object contains unparsed element: map[password:{{ MY_PASSWORD }} username:{{ MY_USER }}]
```

**Comment by skarimo** [comment] 2024-04-25 17:39
@charlesverdad thanks for the report. This is unrelated to the original issue raised, however we are looking into it and will follow up.

**Comment by gpkfr** [comment] 2024-05-02 08:51
the same error occurs on "datadog_logs_archive" :
provider version : 3.39.0

" Error: object contains unparsed element: map[bucket:datadog-rehydrate-tf integration:map[] path:/prod-xenon type:s3]"

**Comment by HantingZhang2** [comment] 2024-05-23 16:29
Hi @gpkfr and @charlesverdad , while we investigate the unparsed element issue for the 2 resources, would you mind open up a new issue each with more information such as the tf file you used ? This would also help with tracking because the root cause might be different, thanks.

**Comment by nkzou** [comment] 2024-06-24 20:53
Closing this issue, as the original issue is resolved. If you have additional unparsed object errors in other resources, please open a new issue.

**Closed by nkzou** 2024-06-24 20:53 UTC
Labels: bug

**Comment by lloydmanansala** [comment] 2024-11-14 17:02
> Closing this issue, as the original issue is resolved. If you have additional unparsed object errors in other resources, please open a new issue.

I still got the same issue, please check: https://github.com/DataDog/terraform-provider-datadog/issues/2673
