### ISSUE TITLE
OAuth 2.0 terraform import

### ISSUE THREAD

**Issue by leandroscardua** [DataDog/terraform-provider-datadog#1598] opened 2022-10-13 13:01 UTC
Hi There,

I tried to create a new datadog_synthetics_test with OAth 2.0 configuration with terraform, but unfortunately I'm not able to create with terraform, only with UI.
I did a test, try to create the resource on UI and try to import it and I`m receiving an error, as you can see below.

Could you please provide a way to deploy a datadog_synthetics_test with OAth 2.0?

### Terraform Version

Terraform v1.0.6
on darwin_amd64
+provider register.terraform.io/datadog/datadog v3.16.0

### Affected Resource(s)

Please list the resources as a list, for example:

-   datadog_synthetics_test

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
```

### Debug Output

Error: object contains unparsed element: map[accessTokenUrl: [https://(removed)](https://%28removed%29/) clientId:(removed) clientSecret: (removed) tokenApiAuthentication:header type:oauth-cliet]

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

Create a OAth 2.0 configuration

### Actual Behavior

Error when import

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform import`

**Comment by therve** [comment] 2022-11-18 15:29
Closing at duplicate of #1612

**Closed by therve** 2022-11-18 15:29 UTC
