### ISSUE TITLE
Support tags in provider configuration

### ISSUE THREAD

**Issue by berniedurfee-renaissance** [DataDog/terraform-provider-datadog#2112] opened 2023-09-19 14:36 UTC
### What resources or data sources are affected?

Provider configuration

### Feature Request

It's nice sometimes to have common tags applied across all resources being created. Some examples would be:

- env:prod
- managed_by:terraform

The AWS provider supports this with the `default_tags` attribute in the provider config.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags

**Comment by skarimo** [comment] 2023-09-19 15:00
Duplicate of https://github.com/DataDog/terraform-provider-datadog/issues/1478. Closing in favor of the former thanks

**Closed by skarimo** 2023-09-19 15:00 UTC
Labels: feature-request
