### ISSUE TITLE
Modify downtime in loop not work.

### ISSUE THREAD

**Issue by Le0exxx** [DataDog/terraform-provider-datadog#310] opened 2019-09-02 10:35 UTC
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
datadog_downtime

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_version = "= 0.10.8"

  backend "s3" {
    bucket         = "terraform-state"
    key            = "xxxx"
    dynamodb_table = "terraform-state-xx"
    region         = "xxx"
    encrypt        = "1"
    profile        = "xxx"
  }
}```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
Every time we run apply on downtime in a loop, it will give us below errors. Note:  "This only happened when we try modify the downtime, new creation is fine." Also if you don't do it in count loop, it also work.

```* datadog_downtime.microservice_monitor_muted[15]: 1 error(s) occurred:

* datadog_downtime.microservice_monitor_muted.15: error updating downtime: API error 502 Bad Gateway: <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Datadog is Down</title>
    <style>
        /* 960 stuff: */
        /* reset */
        html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,font,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td{margin:0;padding:0;border:0;outline:0;font-size:100%;vertical-align:baseline;background:transparent}body{line-height:1}ol,ul{list-style:none}blockquote,q{quotes:none}blockquote:before,blockquote:after,q:before,q:after{content:'';content:none}:focus{outline:0}ins{text-decoration:none}del{text-decoration:line-through}table{border-collapse:collapse;border-spacing:0}
        /* text */
        body{font:13px/1.5 'NotoSans','Lucida Grande','Lucida Sans Unicode',sans-serif}a:focus{outline:1px dotted}hr{border:0 #ccc solid;border-top-width:1px;clear:both;height:0}h1{font-size:25px}h2{font-size:20px}h3{font-size:16px}h4{font-size:14px}h5{font-size:13px}h6{font-size:13px}ol{list-style:decimal}ul{list-style:disc}li{margin-left:30px}p,dl,hr,h1,h2,h3,h4,h5,h6,ol,ul,pre,table,address,fieldset{margin:0 0 16px}
        .clear{clear:both;display:block;overflow:hidden;visibility:hidden;width:0;height:0}
        .clearfix:after{clear:both;content:' ';display:block;font-size:0;line-height:0;visibility:hidden;width:0;height:0}
        * html .clearfix,*:first-child+html .clearfix{zoom:1}
        /* end 960 */
        body {
            color:#333;
            background:#fff;
            min-width:980px;
        }
        a {
            color:#39c;
        }
        a:hover {
            color:#1966aa;
        }
        h1 {
            padding:3px 60px;
            color:#fff;
            background:#443e4a;
            border-bottom:1px solid #543473;
        }
        h1 img {
            vertical-align:baseline;
            margin:0 10px -8px 0;
            height:32px;
        }
        h2 {
            margin:0 0 20px;
            padding:30px 0 0;
            font-size:32px;
            line-height:36px;
        }
        .content {
            padding-left:20em;
            margin:4em auto;
            font-size:16px;
            max-width:50em;
        }
        .nocss {
            display:none;
        }
        ul {
            margin:0;
            padding:0 0 0 2em;
        }
        li {
            margin:0;
            padding:0;
        }
        .hide {
            display:none;
        }
        #color-dot {
            border-radius:99px;
            display:inline-block;
            width:10px;
            height:10px;
            margin-right:5px;
        }
        .critical {
            background-color:#e74c3c;
        }
        .major {
            background-color:#e67e22;
        }
        .minor {
            background-color:#f1c40f;
        }
        .none {
            background-color:#2ecc71;
        }
    </style>
</head>
<body>
    <h1><a href="/"><img src="/static/images/datadog-horizontal-logo.svg" alt="Datadog" /><span class="nocss">Datadog</span></a></h1>
    <div class="content">
        <img src="/static/images/datadog-error-icon.svg" alt="Sad Bits" style="float:left;margin:0 0 0 -20em;height:295px" />
        <h2>Oops - looks like something went wrong!</h2>
        <ul>
            <li id='live_status' class='hide'>Datadog status:
                <span class="meta">
                    <a href="http://status.datadoghq.com" target="_blank">
                        <span id="color-dot"></span>
                        <span id="status-description"></span>
                    </a>
                </span>
            </li>
            <li id='generic_status'><a href="http://status.datadoghq.com/">Check the Datadog Status Page &rarr;</a></li>
            <li>Follow <a href="http://twitter.com/datadogops">@datadogops</a> for status updates</li>
            <li>Email us at <a href='mailto:support@datadoghq.com'>support@datadoghq.com</a></li>
            <li><a href="javascript:void(0)" onclick="location.reload()" style="text-decoration:underline">Try Datadog again &rarr;</a>
        </ul>
        <div class="maint">
            <h2 id='sched_maint' class='hide'>Scheduled Maintenance</h2>
            <div id="maint-description"></div>
            <p id='statuspage_link' class='hide'>See the <a href='http://status.datadoghq.com'>Datadog Status Page</a> for more info.</p>
        </div>
    </div>

    <script src="https://cdn.statuspage.io/se-v2.js" type="text/javascript"></script>
    <script>
        function htmlEscape(str) {
            return String(str).replace(/&/g, '&amp;')
                              .replace(/"/g, '&quot;')
                              .replace(/'/g, '&#39;')
                              .replace(/</g, '&lt;')
                              .replace(/>/g, '&gt;');
        }

        if (typeof StatusPage !== 'undefined') {
            var sp = new StatusPage.page({ page: '1k6wzpspjf99' });
            sp.status({
                success: function(data) {
                    status_indicator = String(data.status.indicator);
                    if (status_indicator && status_indicator.toLowerCase() !== 'none') {
                        document.getElementById('color-dot').className = htmlEscape(status_indicator);
                        document.getElementById('status-description').innerHTML = htmlEscape(data.status.description);
                        document.getElementById('live_status').className = '';
                        document.getElementById('generic_status').className = 'hide';
                    }
                }
            });
            sp.scheduled_maintenances({
                filter: 'active',
                success: function(data) {
                    if (
                        data &&
                        data.scheduled_maintenances &&
                        data.scheduled_maintenances.length > 0 &&
                        data.scheduled_maintenances[0].incident_updates &&
                        data.scheduled_maintenances[0].incident_updates.length > 0
                    ) {
                        document.getElementById('sched_maint').className = '';
                        document.getElementById('statuspage_link').className = '';
                        var desc = document.getElementById('maint-description');
                        incident_text =
                            '<p><b>Scheduled Start:</b> ' +
                            htmlEscape(data.scheduled_maintenances[0].scheduled_for);
                        incident_text +=
                            '</p><p><b>Scheduled End:</b> ' +
                            htmlEscape(data.scheduled_maintenances[0].scheduled_until);
                        incident_text += '</p>';
                        data.scheduled_maintenances[0].incident_updates.forEach(function(incident) {
                            incident_text += '<p>';
                            incident_text += htmlEscape(incident.body);
                            incident_text += '</p>';
                        });

                        desc.innerHTML = String(incident_text).replace(/\n/g, '<br />');
                    }
                }
            });
        }

        setTimeout(function() {
            location.reload()
        }, 60 * 1000);
    </script>

    <!-- begin olark code -->
    <script data-cfasync="false" type='text/javascript'>/*{literal}<![CDATA[*/
        window.olark||(function(c){var f=window,d=document,l=f.location.protocol=="https:"?"https:":"http:",z=c.name,r="load";var nt=function(){f[z]=function(){(a.s=a.s||[]).push(arguments)};var a=f[z]._={},q=c.methods.length;while(q--){(function(n){f[z][n]=function(){f[z]("call",n,arguments)}})(c.methods[q])}a.l=c.loader;a.i=nt;a.p={0:+new Date};a.P=function(u){a.p[u]=new Date-a.p[0]};function s(){a.P(r);f[z](r)}f.addEventListener?f.addEventListener(r,s,false):f.attachEvent("on"+r,s);var ld=function(){function p(hd){hd="head";return["<",hd,"><\/",hd,"><",i,' onl' + 'oad="var d=',g,";d.getElementsByTagName('head')[0].",j,"(d.",h,"('script')).",k,"='",l,"//",a.l,"'",'"',"><\/",i,">"].join("")}var i="body",m=d[i];if(!m){return setTimeout(ld,100)}a.P(1);var j="appendChild",h="createElement",k="src",n=d[h]("div"),v=n[j](d[h](z)),b=d[h]("iframe"),g="document",e="domain",o;n.style.display="none";m.insertBefore(n,m.firstChild).id=z;b.frameBorder="0";b.id=z+"-loader";if(/MSIE[ ]+6/.test(navigator.userAgent)){b.src="javascript:false"}b.allowTransparency="true";v[j](b);try{b.contentWindow[g].open()}catch(w){c[e]=d[e];o="javascript:var d="+g+".open();d.domain='"+d.domain+"';";b[k]=o+"void(0);"}try{var t=b.contentWindow[g];t.write(p());t.close()}catch(x){b[k]=o+'d.write("'+p().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};ld()};nt()})({loader: "static.olark.com/jsclient/loader0.js",name:"olark",methods:["configure","extend","declare","identify"]});
        olark.identify('2947-345-10-2446');olark.configure('box.corner_position', 'br');/*]]>{/literal}*/
    </script>
    <noscript>
        <a href="https://www.olark.com/site/2947-345-10-2446/contact" title="Contact us" target="_blank">Questions? Feedback?</a> powered by <a href="http://www.olark.com?welcome" title="Olark live chat software">Olark live chat software</a>
    </noscript>
    <!-- end olark code -->

</body>
</html>

* datadog_downtime.microservice_monitor_muted[10]: 1 error(s) occurred:```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
This is the piece of code,

resource "datadog_downtime" "microservice_monitor_muted" {
  count            = "${length(var.microservice_monitor_muted)}"
  scope            = ["*"]

  monitor_tags     = ["service:${element(var.microservice_monitor_muted,count.index)}"]
}

Run apply on above code twice.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by bkabrda** [comment] 2020-02-04 16:11
Hey, thanks for the report. I can't reproduce this issue using Terraform 0.12.9 and DD provider 2.6.0. What version of DD provider did you use to reproduce this? How many items do you have in the var that you're looping? Is this reproducible consistently or intermittent? Thanks!

**Comment by therve** [comment] 2020-07-29 08:23
Closing for now, feel free to reopen with more information. Thanks.

**Closed by therve** 2020-07-29 08:23 UTC
Labels: bug
