### ISSUE TITLE
environment variables not honored by darwin provider build

### ISSUE THREAD

**Issue by gillaminar** [DataDog/terraform-provider-datadog#1713] opened 2023-01-10 08:25 UTC
### Terraform Version

Terraform v1.3.7
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.19.1

### Affected Resource(s)

N/A - this is an authentication problem

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    datadog = {
      source = "DataDog/datadog"
    }
  }
}

provider "datadog" {
  validate = false
}
```

### Debug Output

unfortunately way too sensitive to include fully, but including what I can and saved the file to answer specific questions.

[ddlog.txt](https://github.com/DataDog/terraform-provider-datadog/files/10380534/ddlog.txt)

### Panic Output

no panic output

### Expected Behavior

datadog should have run successfully using environment variable credentials

### Actual Behavior

datadog provider threw. a 403 when accessing resources

### Steps to Reproduce

use HCL above
on MacOS ventura 13.1
with environment variable credentials.

### Important Factoids

I have verified that these credentials work by configuring them explicitly within the provider - they are correct.
The same setup appears to work correctly on my github actions pipeline using environment variables, so I suspect a problem with the darwin build.

**Comment by skarimo** [comment] 2023-01-10 19:15
Hello, I am on m1 darwin_arm64 as well and cannot reproduce this issue. Env variables are properly picked up. I do see some vars in your logs that seem to be related to the keys (var.datadog_app_key).  I would double check your sub modules in this case and ensure none of them are actually passing/over-riding the api/app keys, hosts etc.

**Comment by therve** [comment] 2023-03-22 14:10
Closing for now, feel free to reopen with more information.

**Closed by therve** 2023-03-22 14:10 UTC

**Comment by rbarabas** [comment] 2023-04-06 14:52
Does your key work with curl? I had similar symptoms but the issue ended up being key related. A previously working key that was correctly set needed to be regenerated in Datadog.
