### ISSUE TITLE
Datadog monitor fails to plan when the `scheduling_options.evaluation_window` argument is provided

### ISSUE THREAD

**Issue by aidanmelen** [DataDog/terraform-provider-datadog#2353] opened 2024-04-07 20:24 UTC
### Datadog Terraform Provider Version

v3.38.0

### Terraform Version

v1.7.5

### What resources or data sources are affected?

- resource_datadog_monitor

### Terraform Configuration Files

```hcl
resource "datadog_monitor" "foo" {
  name               = "Name for monitor foo"
  type               = "metric alert"
  message            = "Monitor triggered. Notify: @hipchat-channel"
  escalation_message = "Escalation message @pagerduty"

  query = "avg(last_1h):avg:aws.ec2.cpu{environment:foo,host:foo} by {host} > 4"

  scheduling_options {
    evaluation_window {
      hour_starts = 0
    }
  }

  tags = local.tags
}
```

### Relevant debug or panic output

```bash
╷
│ Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors":["Monitors with an evaluation_window scheduling_option must have a current query period and vice versa."]}
│ 
│   with datadog_monitor.foo,
│   on main.tf line 58, in resource "datadog_monitor" "foo":
│   58: resource "datadog_monitor" "foo" {
│ 
╵
```

### Expected Behavior

Create a monitor with the `scheduling_options.evaluation_window` option as documented [here](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor#nested-schema-for-scheduling_optionsevaluation_window).

### Actual Behavior

The plan fails. Unable to create monitor with any `scheduling_options.evaluation_window` configuration.

### Steps to Reproduce

```console
$ terraform plan

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: error validating monitor from https://api.datadoghq.com/api/v1/monitor/validate: 400 Bad Request: {"errors":["Monitors with an evaluation_window scheduling_option must have a current query period and vice versa."]}
│ 
│   with datadog_monitor.foo,
│   on main.tf line 58, in resource "datadog_monitor" "foo":
│   58: resource "datadog_monitor" "foo" {
│ 
╵
```

### Important Factoids

This works with `scheduling_options.custom_schedule.recurrences`.

**Comment by skarimo** [comment] 2024-04-11 20:49
Hello, looks like your query is wrong and needs to be updated to:
```
query = "avg(current_1h):avg:aws.ec2.cpu{environment:foo,host:foo} by {host} > 4"
```

Since the issue is related to monitor query usage rather than the datadog terraform provider, Im going to go ahead and close this issue. Feel free to reach out to our support team if you have further questions: https://www.datadoghq.com/support/

**Closed by skarimo** 2024-04-11 20:49 UTC
Labels: bug

**Comment by aschade92** [comment] 2025-01-28 23:59
I'm having the same issue with a query that works through the datadog UI but not through the terraform provider. Any idea how to fix this query?

```
logs(\"service:service-foo \\\"search string\\\"\").index(\"*\").rollup(\"count\").by(\"env\").last(\"1d\") > 0
```
