### ISSUE TITLE
Terraform Plan fails for "datadog_synthetics_test" resource after upgrading to 3.44.0 (3.43.1 OK) bug

### ISSUE THREAD

**Issue by alexkunde** [DataDog/terraform-provider-datadog#2564] opened 2024-09-06 13:04 UTC
### Datadog Terraform Provider Version

3.44.0

### Terraform Version

1.9.0

### What resources or data sources are affected?

datadog_synthetics_test

### Terraform Configuration Files

```hcl
resource "datadog_synthetics_test" "cert_check" {
  name      = "Certificate Check"
  type      = "api"
  subtype   = "ssl"
  status    = "live"
  locations = ["aws:eu-central-1"] # Frankfurt, Germany
  tags      = ["env:dev", "team:test", "service:hallo"]
  message   = "tsetrs"

  request_definition {
    host = "asd.dev.int"
    port = 443
  }

  assertion {
    type     = "certificate"
    operator = "isInMoreThan"
    target   = 21 # days	
  }

  options_list {
    tick_every = 86400
    # no alerting since this is informational only	
  }
}
```

### Relevant debug or panic output

The resource is already present in the terraform state. Planning will result in:

object contains unparsed element: map[config:map[assertions:[map[operator:isInMoreThan target:30 type:certificate]] configVariables:[] request:map[host:a.b.net port:443]] created_at:2024-02-21T07:08:58.674878+00:00 creator:map[email:a@b.de handle:a@b.de name:<nil>] locations:[pl:asd-123] message:{{#is_alert}}{{/is_alert}}{{#is_alert_recovery}}{{/is_alert_recovery}} Notify:@teams-asd-test modified_at:2024-07-19T12:35:29.935811+00:00 monitor_id:1234 name:[TEST] asd-service Certificate Check options:map[httpVersion:any min_location_failed:1 tick_every:86400] public_id:123 status:live subtype:ssl tags:[env:test team:asd service:asd-service] type:api]

**Comment by GMartinez-Sisti** [comment] 2024-09-06 16:10
This looks like a duplicate of https://github.com/DataDog/terraform-provider-datadog/issues/2561.

**Comment by alexkunde** [comment] 2024-09-06 17:26
It probably is, backend wise

**Comment by nkzou** [comment] 2024-09-10 15:25
Hi, i've been able to reproduce the issue, currently investigating this with the backend team.

**Closed** 2024-09-11 21:06 UTC
Labels: bug

**Comment by nkzou** [comment] 2024-09-11 21:44
Hi all, version 3.44.1 has been released with a fix for this issue. Please try it out and let us know if anything is amiss. Thanks!

**Comment by francovp** [comment] 2024-09-11 22:23
Hello @nizox. After upgrading to 3.44.1, I begin to receive this errors
> 400 Bad Request: {"errors":["'port' value '0' is invalid\nAdditional properties are not allowed ('dnsServerPort' was unexpected)"]}

This is my "request_definition" block

```hcl
request_definition {
    dns_server_port         = "0"
    method                  = "GET"
    no_saving_response_body = "false"
    number_of_packets       = "0"
    persist_cookies         = "false"
    port                    = "0"
    should_track_hops       = "false"
    timeout                 = "0"
    url                     = "http://example.com"
  }
  ```

**Comment by nkzou** [comment] 2024-09-12 13:59
`dnsServerPort` is only valid to set if your test subtype is `dns` - is this the case?. Port value `0` is an invalid option for synthetics tests as far as I'm aware - it's not possible to set it to zero on the web app either.

**Comment by nkzou** [comment] 2024-09-12 15:38
I'm not able to reproduce the behavior you're seeing - could you provide some example terraform configs that have this problem?

**Comment by alexkunde** [comment] 2024-09-12 16:14
For me the 3.44.1 works now, thank you!

**Comment by francovp** [comment] 2024-09-13 14:54
> I'm not able to reproduce the behavior you're seeing - could you provide some example terraform configs that have these problems?

Hello @nkzou, after checking again, I realized that `port` and `dns_server_port` were indeed present in the synthetic tests when the `apply` was failing with the error `"'port' value '0' is invalid\nAdditional properties are not allowed ('dnsServerPort' was unexpected)"]`. I was looking at a different version of the code where they had been removed. Sorry for that.

But now, I have another problem: To fix the pipeline (so other devs can deploy changes), we removed the problematic synthetic tests from the "state" and deleted the resources from the code. Also, *almost all the resources had `import` blocks associated with them because they were imported from Datadog in the past, so we removed those too. After the pipeline was green, I reverted the changes in another branch, added the missing import blocks, and ran `terraform plan`—and now I’m getting a provider crash:

First lot of these "Plugin did not respond" and "Request cancelled"
```hcl
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
```
```hcl
│ Error: Request cancelled
│ 
│   with datadog_monitor.example,
│   on monitors.tf line 1, in resource "datadog_monitor" "example":
│    1: resource "datadog_monitor" "example" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
```

and then

```hcl
Stack trace from the terraform-provider-datadog_v3.44.1 plugin:
panic: runtime error: index out of range [0] with length 0
goroutine 29932 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.buildTerraformConfigVariables({0xc000d0da40, 0x4, 0x9?}, {0x2aff500, 0x0, 0x0?})
	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:2915 +0x63c
github.com/terraform-providers/terraform-provider-datadog/datadog.updateSyntheticsAPITestLocalState(0xc0030f6400, 0xc002472b70)
	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:1798 +0xcd1
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogSyntheticsTestRead({0x1c693c0?, 0xc002c498f0?}, 0xc0030f6400, {0x1587980?, 0xc000444240?})
	github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_synthetics_test_.go:1465 +0x99a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0003c5ce0, {0x1c693c0, 0xc002c498f0}, 0xc0030f6400, {0x1587980, 0xc000444240})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:750 +0x119
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0003c5ce0, {0x1c693c0, 0xc002c498f0}, 0xc001f41930, {0x1587980, 0xc000444240})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:1044 +0x525
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00040dcf8, {0x1c693c0?, 0xc002c49830?}, 0xc00533b840)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:616 +0x4aa
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ReadResource({0xc00033b2f0, 0xc00033b350, {0xc000b2b040, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
	github.com/hashicorp/terraform-plugin-mux@v0.8.0/tf5muxserver/mux_server_ReadResource.go:26 +0xf3
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000e701e0, {0x1c693c0?, 0xc002c48450?}, 0xc000400ea0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/tf5server/server.go:751 +0x46f
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x18e09c0, 0xc000e701e0}, {0x1c693c0, 0xc002c48450}, 0xc004980230, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.18.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:386 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e0000, {0x1c703e0, 0xc000f0a820}, 0xc005291560, 0xc00044e390, 0x2acbe90, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1335 +0xdb8
google.golang.org/grpc.(*Server).handleStream(0xc0001e0000, {0x1c703e0, 0xc000f0a820}, 0xc005291560, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1712 +0x9da
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.3/server.go:947 +0xaf
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 99
	google.golang.org/grpc@v1.56.3/server.go:958 +0x136
Error: The terraform-provider-datadog_v3.44.1 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
2024/09/13 14:32:19.144811 [ERR] (cli) unexpected exit from subprocess (1)
```

Maybe this needs another Bug report in a separated Issue? 
Sorry for taking your time with this, but now we can't restore those synthetics tests to the state because of this problem. 

Thank you for your pacience.

**Comment by etnbrd** [comment] 2024-09-17 08:11
Hey @francovp 👋 
The issue you're having might be worth another but report, so that we can track it independently. This one was closed already.
We have an idea of where the bug is coming from, but what would tremendously help us, is for you to find which tests are failing to be imported this way. It might be many tests, if so, just one or a few examples would be fine. If the information is sensitive, don't hesitate to reach directly to the support, instead of through github tickets.

For future reference, most likely `oldConfigVariables` is empty, so when accessing it [here](https://github.com/DataDog/terraform-provider-datadog/blob/f974a0015bc6fe6ae7b5c6379e50ad33ad664d27/datadog/resource_datadog_synthetics_test_.go#L2915-L2916) fails with an out of range error, which matches the fact that the state was emptied.
