### ISSUE TITLE
Feature Request:  Audit Trail Settings

### ISSUE THREAD

**Issue by jfreeland** [DataDog/terraform-provider-datadog#1594] opened 2022-10-06 18:22 UTC
It would be great to see Audit Trail Settings support in the Datadog terraform provider.

# References

* https://docs.datadoghq.com/account_management/audit_trail/
* https://app.datadoghq.com/organization-settings/audit-trail-settings

**Comment by JeanFred** [comment] 2023-03-22 12:23
Duplicate of #1456?

**Comment by therve** [comment] 2023-03-22 14:11
Closing in favor of #1456, thanks.

**Closed by therve** 2023-03-22 14:11 UTC
