### ISSUE TITLE
The terraform-provider-datadog_v3.21.0 plugin crashed

### ISSUE THREAD

**Issue by sipahisnm** [DataDog/terraform-provider-datadog#1926] opened 2023-05-19 18:54 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/datadog/datadog v3.21.0
+ provider registry.terraform.io/hashicorp/aws v4.57.0

Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

datadog_logs_custom_pipeline

Please list the resources as a list, for example:

-   opc_instance
-   opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

**NOTE:** Remember to review debug output before posting, and redact any sensitive data.

Stack trace from the terraform-provider-datadog_v3.21.0 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 124 [running]:
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogGrokParser(0x5000?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:938 +0x564
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogProcessor({0x100ec1f47?, 0x1400058d9b0?}, 0x1014ee1d0?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:775 +0x184
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogProcessors({0x140005d0690, 0x3, 0x100ebb5eb?})
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:740 +0x150
github.com/terraform-providers/terraform-provider-datadog/datadog.buildDatadogPipeline(0x14000e3ac98?)
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:726 +0x2c4
github.com/terraform-providers/terraform-provider-datadog/datadog.resourceDatadogLogsPipelineCreate({0x1014e9e60?, 0x14000bbc7b0?}, 0x0?, {0x10119bca0?, 0x14000b1e450?})
        github.com/terraform-providers/terraform-provider-datadog/datadog/resource_datadog_logs_custom_pipeline.go:370 +0x114
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400039e000, {0x1014e9e60, 0x14000bbc7b0}, 0xd?, {0x10119bca0, 0x14000b1e450})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:707 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400039e000, {0x1014e9e60, 0x14000bbc7b0}, 0x14000417ee0, 0x14000b1b600, {0x10119bca0, 0x14000b1e450})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/resource.go:837 +0x874
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x1400000c018, {0x1014e9e60?, 0x14000bbc690?}, 0x140005b5720)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.0/helper/schema/grpc_provider.go:1021 +0xb94
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140004520a0, {0x1014e9e60?, 0x14000b61a40?}, 0x14000164690)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/tf5server/server.go:818 +0x3c0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1014287a0?, 0x140004520a0}, {0x1014e9e60, 0x14000b61a40}, 0x14000164620, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000488000, {0x1014ecaa0, 0x140006836c0}, 0x14000ae3c20, 0x140003e7a40, 0x101f8d420, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1295 +0x9d8
google.golang.org/grpc.(*Server).handleStream(0x14000488000, {0x1014ecaa0, 0x140006836c0}, 0x14000ae3c20, 0x0)
        google.golang.org/grpc@v1.48.0/server.go:1636 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.48.0/server.go:932 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.48.0/server.go:930 +0x298

Error: The terraform-provider-datadog_v3.21.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

**NOTE:** Remember to review panic log file before posting, and redact any sensitive data.

### Expected Behavior

What should have happened?

### Actual Behavior

What actually happened?

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:

-   GH-1234

**Comment by nkzou** [comment] 2023-05-19 19:47
Hi, from what I can tell this issue was fixed by #1917, and it's caused by empty strings in the `samples` field. We haven't released a version with the fix yet, but we expect to release in 2 weeks. In the meantime you can avoid the issue by making sure there is no empty string in `samples` like so -
```
processor {
    grok_parser {
      samples = []
      ...
    }
  }
```
If this didn't solve your issue, please share a snippet of your pipeline definition. Thanks!

**Closed by nkzou** 2023-05-19 19:47 UTC
